name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Vérifier le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configurer Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construire l'image Docker
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    # Pousser l'image sur Docker Hub
    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
