name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Remplacez par la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout le code de votre dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Installer Docker sur la machine runner si nécessaire
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Mise en cache des couches Docker pour optimiser les builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Connexion à Docker Hub avec les secrets GitHub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construire l'image Docker
    - name: Build Docker image
      run: |
        cd /home/ubunto/Téléchargements/flask-app-swarm-main  # Naviguer vers votre répertoire de travail
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    # Pousser l'image Docker dans Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
