name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Remplacez par la branche de votre choix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code source du dépôt
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurer Docker Buildx pour une meilleure gestion des builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Mettre en cache les couches Docker pour améliorer la vitesse des builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Se connecter à Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construire l'image Docker
    - name: Build Docker image
      run: |
        # Le répertoire du dépôt cloné est déjà le répertoire de travail
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    # Pousser l'image Docker vers Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
